---

# Main playbook to set up kubernetes environment

- name: Prepare servers to install kuberentes
  become: yes
  become_user: root
  hosts:
    - all
  roles:
    - common

- name: Provision Kubernetes master node
  become: yes
  become_user: root
  vars_files:
    - conf_vars.yml
  hosts:
    - etcd
  roles:
    - etcd
