---
# tasks to install etcd

- name: Include Configuration
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
  when: not etcd_config_only|bool

- name: Install system dependencies for synchronize
  package: name={{ item }}
  with_flattened: "{{ etcd_install_dependencies|default([]) }}"
  when: not etcd_config_only|bool

- name: Install etcd from RHEL7 packages
  yum:
    pkg=etcd
    state=latest
  when: not is_atomic

- name: Make etcd data dir
  file:
    path={{ etcd_data_dir }}
    state=directory

- name: Write etcd config file
  template:
    src={{ env_file_template }}
    dest={{ env_file }}
  # Allways restart the service
  changed_when: yes
  notify:
    - restart etcd
