---
# tasks to install etcd

- name: Install etcd from RHEL7 packages
  yum:
    pkg=etcd
    state=latest
  when: not is_atomic
  # Allways change status, so the handlers are notified
  changed_when: yes
  notify:
    - enable etcd
    - restart etcd

- name: Make etcd data dir
  file:
    path={{ etcd_data_dir }}
    state=directory

- name: Write etcd config file
  template:
    src={{ env_file_template }}
    dest={{ env_file }}
  # Allways restart the service
  changed_when: yes
  notify:
    - restart etcd
