---
# tasks to install etcd

- name: Install etcd from RHEL7 packages
  yum:
    pkg=etcd
    state=latest
  when: not is_atomic
  # Allways change status, so the handlers are notified
  changed_when: yes
  notify:
    - enable etcd
    - restart etcd

- name: Write etcd config file for version 2.0.x
  template:
    src=etcd.20.conf.j2
    dest=/etc/etcd/etcd.conf
  notify:
    - restart etcd
