---

- name: Write etcd config file for version 2.0.x
  template:
    src=kuber_apiserver.j2
    dest=/etc/kubernetes/apiserver

- debug: msg='Restart and enable kubernetes services'
  notify:
    - restart kube-apiserver
    - restart kube-controller-manager
    - restart kube-scheduler
  changed_when: true
