---

# Configure
#   - kubelete
#   - kube-proxy

- name: Install kubernetes
  package: name={{ item }}
  with_flattened: "{{ kube_minion_install_packages | default([]) }}"
  when: not kube_config_only | bool

- name: set master ip address
  set_fact:
    master_ip: >
      '{{ hostvars[groups["Master"][0]]
         ['ansible_eth1']['ipv4']['address'] }}'

- name: Write etcd config file for version 2.0.x
  template:
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - src: kube_config.j2
      dest: /etc/kubernetes/config
    - src: kube_kubelete.j2
      dest: /etc/kubernetes/kubelet

- debug: msg='Restart and enable kubernetes services'
  notify:
    - restart kubelet
    - restart kube-proxy
  changed_when: true
