---

#  Configure:
#   - acpi
#   - control
#   - scheduler

- name: Write apiserver config file
  template:
    src={{ kube_api_file }}
    dest={{ kube_api_path }}

- debug: msg='Restart and enable kubernetes services'
  notify:
    - restart kube-apiserver
    - restart kube-controller-manager
    - restart kube-scheduler
  changed_when: true
