---

# Configure
#   - kubelete
#   - kube-proxy

- name: Install kubernetes
  package: name={{ item }}
  with_flattened: "{{ kube_minion_install_packages | default([]) }}"
  when: not kube_config_only | bool

- name: Write apiserver config file
  template:
    src={{ item.file }}
    dest={{ item.path }}
  with_items: "{{ kube_minion_conf_services }}"

- debug: msg='Restart and enable kubernetes services'
  notify:
    - restart kubelet
    # - restart kube-proxy
  changed_when: true
