---
# tasks file for kubernetes

- name: Install kubernetes
  package:
    name=kubernetes
    state=latest
  when: not is_atomic

- include: kuber_master.yml
  when: "'Master' in group_names"

- include: kuber_minion.yml
  when: "'Minions' in group_names"
