---

- name: Copy the configure script
  template:
    src={{ item.file }}
    dest={{ item.path }}
    mode=0755
  with_items:
    - file: "{{ flannel_config_json_j2 }}"
      path: "{{ flannel_netconf_path }}"
    - file: "{{ flannel_script_file }}"
      path: "{{ flannel_script_path }}"
  notify:
    - flannel etcd network

- name: Remove the configure files
  file:
    name={{ item }}
    state=absent
  with_items:
    - "{{ flannel_script_path }}"
    - "{{ flannel_netconf_path }}"
