---

- name: Install flannel
  package:
    name=flannel
    state=latest
  when: not is_atomic

- name: Write flanneld config file
  template:
    src={{ flanneld_config_file }}
    dest={{ flanneld_config_path }}
  notify:
    - restart flannel
